### ISSUE TITLE
Do We Need to Use Dropout after the Pooling Layer?

### ISSUE THREAD

**Issue by CosmoChan** [mollymr305/mnist-mc-dropout#1]
Thank you for sharing! 
But according to Yarin Gal's code
(https://github.com/yaringal/DropoutUncertaintyCaffeModels/blob/master/mnist_uncertainty/lenet_all_dropout_deploy.prototxt), 
I think dropout is not needed after max pooling layer, do I understand correctly?

**Comment by mollymr305** [comment]
@CosmoChan thank you for your comment. This repository was part of an old project of mine. It was not my intention to exactly replicate the model shown in your link. The network architecture/parameters were chosen quite arbitrarily actually, and my main purpose was to explore "Monte Carlo dropout" as a general classification principle.
